version: "3"
services:
  python2:
    build:
      context: .
      dockerfile: ./dockerfiles/python2.7/Dockerfile
    env_file:
      - .env
    volumes:
      - .:/src
    stdin_open: true
    tty: true
  python3:
    build:
      context: .
      dockerfile: ./dockerfiles/python3.7/Dockerfile
    env_file:
      - .env
    volumes:
      - .:/src
    stdin_open: true
    tty: true
