version: 2

# Base python 3 setup
python3: &python3
  working_directory: ~/repo
  docker:
    # the Docker image with Cypress dependencies
    - image: python:3.7
      auth:
        username: $DOCKERHUB_USER
        password: $DOCKERHUB_PASSWORD
      environment:
        ## this enables colors in the output
        TERM: xterm

# Base python 2 setup
python2: &python2
  working_directory: ~/repo
  docker:
    # the Docker image with Cypress dependencies
    - image: python:2.7
      auth:
        username: $DOCKERHUB_USER
        password: $DOCKERHUB_PASSWORD
      environment:
        ## this enables colors in the output
        TERM: xterm

jobs:
  build:
    # Main build process
    <<: *python3
    steps:
      - checkout
      - restore_cache:
          key: deps3_7-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Pip Install
          command: pip install -r requirements.txt
      - save_cache:
          key: deps3_7-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
      - run:
          name: Build dist
          command: python setup.py sdist bdist_wheel
      - run:
          name: Check dist
          command: python -m twine check dist/*
      - persist_to_workspace:
          root: ~/repo
          paths:
            - dist

  test_python2:
    # Main build process
    <<: *python2
    steps:
      - checkout
      - restore_cache:
          key: deps2_7-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Pip Install
          command: pip install -r requirements.txt
      - save_cache:
          key: deps2_7-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "/usr/local/bin"
            - "/usr/local/lib/python2.7/site-packages"
      - run:
          name: Run Tests
          command: python test.py
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1

  test_python3:
    # Main build process
    <<: *python3
    steps:
      - checkout
      - restore_cache:
          key: deps3_7-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Pip Install
          command: pip install -r requirements.txt
      - save_cache:
          key: deps3_7-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
      - run:
          name: Run Tests
          command: python test.py
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1

  deploy_test:
    # Main build process
    <<: *python3
    steps:
      # Checkout git repo
      - checkout
      - restore_cache:
          key: deps3_7-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Pip Install
          command: pip install -r requirements.txt
      - save_cache:
          key: deps3_7-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
      # Attach the public repo created in the build task
      - attach_workspace:
          at: ~/repo
      - run:
          name: Upload to PYPI test
          command: python -m twine upload --repository-url https://test.pypi.org/legacy/ dist/*

  deploy:
    # Main build process
    <<: *python3
    steps:
      # Checkout git repo
      - checkout
      - restore_cache:
          key: deps3_7-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Pip Install
          command: pip install -r requirements.txt
      - save_cache:
          key: deps3_7-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
      # Attach the public repo created in the build task
      - attach_workspace:
          at: ~/repo
      - run:
          name: Upload to PYPI
          command: python -m twine upload --repository-url https://upload.pypi.org/legacy/ dist/*

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          context:
            - hubblehq-docker
      - test_python2:
          context:
            - hubblehq-docker
      - test_python3:
          context:
            - hubblehq-docker
      - deploy_test:
          context:
            - hubblehq-docker
          requires:
            - build
            - test_python2
            - test_python3
          filters:
            branches:
              only: master
      - deploy:
          context:
            - hubblehq-docker
          requires:
            - deploy_test
          filters:
            branches:
              only: master
