version: 2

jobs:
  build_python2:
    # Main build process
    working_directory: ~/repo
    docker:
      # the Docker image with Cypress dependencies
      - image: python:2.7
        environment:
          ## this enables colors in the output
          TERM: xterm
    steps:
      - checkout
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python2.7/site-packages"
      - run:
          command: |
            pipenv run "python test.py"
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1

  build_python3:
    # Main build process
    working_directory: ~/repo
    docker:
      # the Docker image with Cypress dependencies
      - image: python:3.6
        environment:
          ## this enables colors in the output
          TERM: xterm
    steps:
      - checkout
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
      - run:
          command: |
            pipenv run "python test.py"
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_python2
      - build_python3

