version: 2

jobs:
  build_python2:
    # Main build process
    working_directory: ~/repo
    docker:
      # the Docker image with Cypress dependencies
      - image: python:2.7
        environment:
          ## this enables colors in the output
          TERM: xterm
    steps:
      - checkout
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Pip Install
          command: pip install -r requirements.txt
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "/usr/local/bin"
            - "/usr/local/lib/python2.7/site-packages"
      - run:
          name: Run Tests
          command: python test.py
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1

  build_python3:
    # Main build process
    working_directory: ~/repo
    docker:
      # the Docker image with Cypress dependencies
      - image: python:3.7
        environment:
          ## this enables colors in the output
          TERM: xterm
    steps:
      - checkout
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Pip Install
          command: pip install -r requirements.txt
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
      - run:
          name: Run Tests
          command: python test.py
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_python2
      - build_python3
